version: "3"

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        PYTHON_VARIANT: 3.10.7
      target: ap_playground_base
    volumes:
      - ..:/workspace:cached
    command: sleep infinity